# Generated by Django 5.2.7 on 2025-10-27 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="createdAt", null=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_column="updatedAt", null=True
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("bank", "Bank"),
                            ("credit_card", "Credit Card"),
                            ("wallet", "Wallet"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                ("currency", models.CharField(blank=True, max_length=3, null=True)),
                (
                    "balance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(db_column="isDefault", default=False),
                ),
            ],
            options={
                "db_table": "accounts",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="createdAt", null=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_column="updatedAt", null=True
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "role",
                    models.IntegerField(
                        choices=[(0, "User"), (1, "Admin"), (2, "Manager")], default=0
                    ),
                ),
            ],
            options={
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="createdAt", null=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_column="updatedAt", null=True
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_column="isActive", default=True)),
                (
                    "user",
                    models.ForeignKey(
                        db_column="userId",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "db_table": "projects",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="createdAt", null=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_column="updatedAt", null=True
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "kind",
                    models.CharField(
                        choices=[("income", "Income"), ("expense", "Expense")],
                        max_length=16,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="userId",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "db_table": "categories",
            },
        ),
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="createdAt", null=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_column="updatedAt", null=True
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "warn_at_percent",
                    models.DecimalField(
                        blank=True,
                        db_column="warnAtPercent",
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "max_per_txn",
                    models.DecimalField(
                        blank=True,
                        db_column="maxPerTxn",
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    "period_start",
                    models.DateField(blank=True, db_column="periodStart", null=True),
                ),
                (
                    "period_end",
                    models.DateField(blank=True, db_column="periodEnd", null=True),
                ),
                (
                    "last_alert_sent",
                    models.DateTimeField(
                        blank=True, db_column="lastAlertSent", null=True
                    ),
                ),
                ("is_active", models.BooleanField(db_column="isActive", default=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        db_column="accountId",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="budgets",
                        to="core.account",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        db_column="categoryId",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="budgets",
                        to="core.category",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        db_column="projectId",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="budgets",
                        to="core.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="userId",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budgets",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "db_table": "budgets",
            },
        ),
        migrations.AddField(
            model_name="account",
            name="user",
            field=models.ForeignKey(
                db_column="userId",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accounts",
                to="core.user",
            ),
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="createdAt", null=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_column="updatedAt", null=True
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("income", "Income"),
                            ("expense", "Expense"),
                            ("transfer", "Transfer"),
                        ],
                        max_length=16,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("currency", models.CharField(blank=True, max_length=3, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("date", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pending", "Pending"),
                            ("cleared", "Cleared"),
                            ("reconciled", "Reconciled"),
                            ("void", "Void"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "receipt_url",
                    models.TextField(blank=True, db_column="receiptUrl", null=True),
                ),
                (
                    "is_recurring",
                    models.BooleanField(db_column="isRecurring", default=False),
                ),
                (
                    "recurring_interval",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("yearly", "Yearly"),
                        ],
                        db_column="recurringInterval",
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "next_recurring_date",
                    models.DateTimeField(
                        blank=True, db_column="nextRecurringDate", null=True
                    ),
                ),
                (
                    "last_processed",
                    models.DateTimeField(
                        blank=True, db_column="lastProcessed", null=True
                    ),
                ),
                (
                    "reimbursed_at",
                    models.DateTimeField(
                        blank=True, db_column="reimbursedAt", null=True
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        db_column="accountId",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="core.account",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        db_column="categoryId",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="core.category",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        db_column="projectId",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="core.project",
                    ),
                ),
                (
                    "to_account",
                    models.ForeignKey(
                        blank=True,
                        db_column="toAccountId",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incoming_transfers",
                        to="core.account",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="userId",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "db_table": "transactions",
                "indexes": [
                    models.Index(
                        fields=["user", "date"], name="transactions_user_date_idx"
                    ),
                    models.Index(
                        fields=["account", "date"], name="transactions_account_date_idx"
                    ),
                    models.Index(
                        fields=["project", "date"], name="transactions_project_date_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="projects_user_name_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                fields=("user", "kind", "name"), name="categories_user_kind_name_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="budget",
            constraint=models.UniqueConstraint(
                fields=(
                    "user",
                    "project",
                    "account",
                    "category",
                    "period_start",
                    "period_end",
                ),
                name="budgets_scope_period_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["user", "is_default"], name="accounts_user_isdefault_idx"
            ),
        ),
    ]
