# Generated by Django 5.2.7 on 2025-11-30 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_role_organization_account_org_budget_org_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('asset_type', models.CharField(choices=[('stock', 'Stock'), ('crypto', 'Crypto'), ('etf', 'ETF')], max_length=10)),
                ('exchange', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'securities',
            },
        ),
        migrations.CreateModel(
            name='MarketDataSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('open', models.DecimalField(decimal_places=4, max_digits=18)),
                ('high', models.DecimalField(decimal_places=4, max_digits=18)),
                ('low', models.DecimalField(decimal_places=4, max_digits=18)),
                ('close', models.DecimalField(decimal_places=4, max_digits=18)),
                ('volume', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='core.security')),
            ],
            options={
                'db_table': 'market_data_snapshots',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['security', '-timestamp'], name='mds_security_ts_idx')],
            },
        ),
        migrations.CreateModel(
            name='SimulatedPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt', null=True)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('avg_price', models.DecimalField(decimal_places=4, max_digits=18)),
                ('current_price', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.organization')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sim_positions', to='core.security')),
                ('user', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='sim_positions', to='core.user')),
            ],
            options={
                'db_table': 'simulated_positions',
                'constraints': [models.UniqueConstraint(fields=('org', 'user', 'security'), name='sim_positions_org_user_security_unique')],
            },
        ),
        migrations.CreateModel(
            name='TradingRuleSim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt', null=True)),
                ('name', models.CharField(max_length=255)),
                ('strategy_type', models.CharField(choices=[('dca', 'Dollar-cost averaging'), ('rebalance', 'Rebalance'), ('threshold_buy', 'Threshold Buy'), ('threshold_sell', 'Threshold Sell')], max_length=32)),
                ('amount_per_run', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('interval', models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=16, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.organization')),
                ('security', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sim_trading_rules', to='core.security')),
                ('user', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='sim_trading_rules', to='core.user')),
            ],
            options={
                'db_table': 'sim_trading_rules',
                'indexes': [models.Index(fields=['org', 'user', 'is_active'], name='sim_rules_org_user_active_idx')],
            },
        ),
    ]
